### ISSUE TITLE
User  is Not Authorized to Join the room

### ISSUE THREAD

**Issue by aravindhu-gloify** [100mslive/100ms-android#13]
I'm able to create an Authorization token, create a room and connect with hmsclient. After that, when I'm trying to join the room then getting the following error

rawData: {"response":true,"id":6104463,"ok":false,"errorCode":-1,"errorReason":"User  is Not Authorized to Join the room {room_id}"}

Integrated version : 'com.github.100mslive:android-sdk:0.9.13'

**Comment by aniketbehera** [comment]
Hey @aravindhu-gloify can you confirm that you are using the client-side token to join the room? 
The token used to create the room is different from client-side token.

The client-side token should look like this (on jwt.io) ->
![image](https://user-images.githubusercontent.com/5078656/108327584-92453c00-71f1-11eb-9a75-858d9bd20d2d.png)

**Comment by aniketbehera** [comment]
@aravindhu-gloify There are 2 kinds of tokens - [client-side token](https://docs.100ms.live/server-side/authentication) and [server-side token](https://docs.100ms.live/server-side/generate-server-side-token)

Server-side token is used to create a room
Client-side token is used by the apps to join a room

A cause of the error can be using the server-side token instead of server-side token.

eg. this is a sample client-side token
![JSON-Web-Tokens-jwt-io](https://user-images.githubusercontent.com/5078656/108327805-d6d0d780-71f1-11eb-8cc5-45e25d913458.png)

**Comment by aniketbehera** [comment]
@aravindhu-gloify We've just fixed an error in our app which might have been causing this issue. 
Can you please take the latest pull and check?
